services:

  postgres:
    image: postgres:16
    container_name: nis2-postgres
    restart: always
    environment:
      POSTGRES_DB: nis2_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nis2-network

  backend:
    build:
      context: ..
    container_name: nis2-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - nis2-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/nis2_platform
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  postgres_data:

networks:
  nis2-network: