services:
  postgres:
    image: postgres:16
    container_name: nis2-postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nis2-network

  mongodb:
    image: mongo:latest
    container_name: nis2-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - nis2-network

volumes:
  postgres_data:
  mongodb_data:

networks:
  nis2-network:
    driver: bridge