spring.application.name=NISync


server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/nis2_platform
spring.datasource.username=swapnil
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api/v1

springdoc.swagger-ui.path=/swagger-ui.html


logging.level.root=INFO
logging.level.com.nisync=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %level - %logger{36} - %msg%n